name: mac
on: 
  workflow_dispatch:
    inputs:
        macOSVersion:
          description: 'macOS Version'
          required: true
          default: 'macos-13'
          type: choice
          options:
          - macos-13
          - macos-12
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ inputs.macOSVersion }}
    environment: ENV_VAR
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
